// Lazy loader for the perry wasm bindings. The wasm/JS glue is generated by
// scripts/build-perry.sh into src/wasm/perry/.

type PerryModule = {
    default: (input?: unknown) => Promise<unknown>;
    perry_eval_expr: (input: string) => string;
    perry_run_file: (input: string) => string;
};

let modulePromise: Promise<PerryModule> | null = null;

async function loadPerry(): Promise<PerryModule> {
    if (!modulePromise) {
        modulePromise = (async () => {
            const mod = (await import('../wasm/perry/perry.js')) as unknown as PerryModule;
            await mod.default();
            return mod;
        })();
    }
    return modulePromise;
}

export function preload(): void {
    void loadPerry();
}

export async function evalExpr(input: string): Promise<{ ok: true; value: string } | { ok: false; error: string }> {
    try {
        const mod = await loadPerry();
        return { ok: true, value: mod.perry_eval_expr(input) };
    } catch (e) {
        return { ok: false, error: extractMessage(e) };
    }
}

export async function runFile(input: string): Promise<{ ok: true; value: string } | { ok: false; error: string }> {
    try {
        const mod = await loadPerry();
        return { ok: true, value: mod.perry_run_file(input) };
    } catch (e) {
        return { ok: false, error: extractMessage(e) };
    }
}

function extractMessage(e: unknown): string {
    if (e instanceof Error) return e.message;
    if (typeof e === 'string') return e;
    return String(e);
}
